### PR TITLE
This upgrades Ext JS to Version 6.2.0

### PR DESCRIPTION
**Pull request by KaiVolland**

### CODE REVIEW

**Comment by annarieger** [comment]
+1 from me, thx for upgrading :pineapple:

**Comment by buehner** [comment]
@KaiVolland Did you quick-check the main functionality of the client? For example the document tree...?

**Comment by KaiVolland** [comment]
Not yet.

**Comment by marcjansen** [comment]
I hear toasts have a different default alignment now... nonetheless,  we can adjust that later, if needed at all. Please merge and thanks.

**Pull request merged**
